#!/bin/bash

x=~/temp/YTdownload.mp4				# temp file in which the data are downloaded

youtube-dl --output=$x --format=18 "$1"		# download the file in highest quality [--format=18]

avconv -i $x -vn -c:a libmp3lame -q:a 4 "$2"	# convert the donwnloaded file from mp4 to mp3 

rm $x						# remove the temp file

# sudo apt-get install python3-pip
# sudo pip3 install --upgrade youtube_dl
# sudo add-apt-repository ppa:heyarje/libav-11 && sudo apt-get update
# sudo apt-get install libav-tools

# if you get "ERROR: unable to download video" 
# update youtube-dl with
# sudo youtube-dl -U
# sudo install yt2mp3 /usr/local/bin
# usage yt2mp3 https://www.youtube.com/watch?v=JBRbGbkZMsQ fileName.mp3
